<?php

namespace AppBundle\Repository;

/**
 * Users_hobbiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Users_hobbiesRepository extends \Doctrine\ORM\EntityRepository
{
}
